# Generated by Django 3.0.7 on 2020-08-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='posted_on',
            field=models.DateTimeField(),
        ),
    ]
