# Generated by Django 3.0.7 on 2020-08-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toyc', '0002_auto_20200806_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
